<a href="https://colab.research.google.com/github/cddogaru/Inteligencia-Artificial-UEM/blob/main/Teoria_de_Juegos_e_Inteligencia_Artificial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install nashpy

In [6]:
import nashpy as nash
import numpy as np

Definimos las matrices de recompensas:

In [7]:
import numpy as np  # Importar numpy
import nashpy as nash  # Importar nashpy

# Definir las matrices de recompensas
A = np.array([[-8, 0], [-10, -11]])  # Jugador filas
B = np.array([[-8, -10], [0, -11]])  # Jugador columnas

# Crear el juego
juego1 = nash.Game(A, B)

# Verificar el juego
juego1


Bi matrix game with payoff matrices:

Row player:
[[ -8   0]
 [-10 -11]]

Column player:
[[ -8 -10]
 [  0 -11]]

Encontramos las estrategias de Equilibrio:

In [8]:
equilibrios = juego1.support_enumeration()
for eq in equilibrios:
    print(eq)

(array([1., 0.]), array([1., 0.]))


De manera similar, para un juego mas complejo con estrategias dominantes:

In [9]:
A2 = np.array([[6, 4, 4, 3],
               [5, 6, 0, 5],
               [5, 3, 6, 4],
               [2, 2, 3, 6]]) # A es el jugador filas.

B2 = np.array([[3, 4, 1, 0],
               [4, 3, 2, 1],
               [0, 2, 1, 4],
               [0, 3, 3, 1]]) # B es el jugador columnas.
juego2 = nash.Game(A2, B2)
juego2

Bi matrix game with payoff matrices:

Row player:
[[6 4 4 3]
 [5 6 0 5]
 [5 3 6 4]
 [2 2 3 6]]

Column player:
[[3 4 1 0]
 [4 3 2 1]
 [0 2 1 4]
 [0 3 3 1]]

Las estrategias resultantes son aquellas que no son dominadas:

In [10]:
equilibrios = juego2.support_enumeration()
for eq in equilibrios:
    print(eq)

(array([0.5, 0.5, 0. , 0. ]), array([0.66666667, 0.33333333, 0.        , 0.        ]))


# Minimax para 3 en Raya

In [ ]:
import time

class Juego:
    def __init__(self):
        self.iniciar_juego()

    def iniciar_juego(self):
        self.estado_actual = [['.','.','.'],
                              ['.','.','.'],
                              ['.','.','.']]

        # X siempre juega primero:
        self.turno_jugador = 'X'

    def dibujar_tablero(self):
        for i in range(0, 3):
            for j in range(0, 3):
                print('{}|'.format(self.estado_actual[i][j]), end=" ")
            print()
        print()

    def es_valido(self, px, py):
      if px < 0 or px > 2 or py < 0 or py > 2:
          return False
      elif self.estado_actual[px][py] != '.':
          return False
      else:
          return True

    def es_fin(self):
      # Victoria en vertical:
      for i in range(0, 3):
          if (self.estado_actual[0][i] != '.' and
              self.estado_actual[0][i] == self.estado_actual[1][i] and
              self.estado_actual[1][i] == self.estado_actual[2][i]):
              return self.estado_actual[0][i]

      # Victoria en Horizontal:
      for i in range(0, 3):
          if (self.estado_actual[i] == ['X', 'X', 'X']):
              return 'X'
          elif (self.estado_actual[i] == ['O', 'O', 'O']):
              return 'O'

      # Victoria diagonal principal:
      if (self.estado_actual[0][0] != '.' and
          self.estado_actual[0][0] == self.estado_actual[1][1] and
          self.estado_actual[0][0] == self.estado_actual[2][2]):
          return self.estado_actual[0][0]

      # Victoria diagonal secundaria:
      if (self.estado_actual[0][2] != '.' and
          self.estado_actual[0][2] == self.estado_actual[1][1] and
          self.estado_actual[0][2] == self.estado_actual[2][0]):
          return self.estado_actual[0][2]

      # Mesa llena:
      for i in range(0, 3):
          for j in range(0, 3):
              # Si hay espacio, seguimos jugando:
              if (self.estado_actual[i][j] == '.'):
                  return None

      # Empate, mesa llena sin victoria:
      return '.'

    # 'O' es max, en este caso la IA:
    def max(self):

        # Posibles valores para max:
        # -1 - pierde
        #  0 - empata
        #  1 - gana

        # Inicializamos el resultado a -2, peor que lo peor
        maxv = -2

        px = None
        py = None

        resultado = self.es_fin()

        # Si el juego acaba, debemos devolver el resultado:
        if resultado == 'X':
            return (-1, 0, 0)
        elif resultado == 'O':
            return (1, 0, 0)
        elif resultado == '.':
            return (0, 0, 0)

        for i in range(0, 3):
            for j in range(0, 3):
                if self.estado_actual[i][j] == '.':
                    # Esto es una rama del juego:
                    self.estado_actual[i][j] = 'O'
                    (m, min_i, min_j) = self.min()
                    # Fijamos maxv si es necesario:
                    if m > maxv:
                        maxv = m
                        px = i
                        py = j
                    # Vaciamos el tablero
                    self.estado_actual[i][j] = '.'
        return (maxv, px, py)

    # El jugador 'X' es min, un humano en este caso:
    def min(self):

        #Inicio igual que para max:
        minv = 2

        qx = None
        qy = None

        resultado = self.es_fin()

        if resultado == 'X':
            return (-1, 0, 0)
        elif resultado == 'O':
            return (1, 0, 0)
        elif resultado == '.':
            return (0, 0, 0)

        for i in range(0, 3):
            for j in range(0, 3):
                if self.estado_actual[i][j] == '.':
                    self.estado_actual[i][j] = 'X'
                    (m, max_i, max_j) = self.max()
                    if m < minv:
                        minv = m
                        qx = i
                        qy = j
                    self.estado_actual[i][j] = '.'

        return (minv, qx, qy)

    def jugar(self):
      while True:
          self.dibujar_tablero()
          self.resultado = self.es_fin()

          # Mostrar que el juego termino:
          if self.resultado != None:
              if self.resultado == 'X':
                  print('El ganador es X!')
              elif self.resultado == 'O':
                  print('El ganador es O!')
              elif self.resultado == '.':
                  print("Empate!")

              self.iniciar_juego()
              return

          # If it's player's turn
          if self.turno_jugador == 'X':

              while True:

                  inicio = time.time()
                  (m, qx, qy) = self.min()
                  fin = time.time()
                  print('Evaluacion: {}s'.format(round(fin - inicio, 7)))
                  print('Movimientos Recomendados: X = {}, Y = {}'.format(qx, qy))

                  px = int(input('X coordenada: '))
                  py = int(input('Y coordenada: '))

                  (qx, qy) = (px, py)

                  if self.es_valido(px, py):
                      self.estado_actual[px][py] = 'X'
                      self.turno_jugador = 'O'
                      break
                  else:
                      print('Movimiento no valido, prueba otra vez.')

          # Turno de la IA
          else:
              (m, px, py) = self.max()
              self.estado_actual[px][py] = 'O'
              self.turno_jugador = 'X'

In [ ]:
g = Juego()
g.jugar()

.| .| .| 
.| .| .| 
.| .| .| 

Evaluacion: 3.2620902s
Movimientos Recomendados: X = 0, Y = 0
X coordenada: 1
Y coordenada: 1
.| .| .| 
.| X| .| 
.| .| .| 

O| .| .| 
.| X| .| 
.| .| .| 

Evaluacion: 0.038965s
Movimientos Recomendados: X = 0, Y = 1
X coordenada: 0
Y coordenada: 0
Movimiento invalido, prueba otra vez.
Evaluacion: 0.0469537s
Movimientos Recomendados: X = 0, Y = 1
X coordenada: 1
Y coordenada: 0
O| .| .| 
X| X| .| 
.| .| .| 

O| .| .| 
X| X| O| 
.| .| .| 

Evaluacion: 0.0016596s
Movimientos Recomendados: X = 0, Y = 1
X coordenada: 0
Y coordenada: 1
O| X| .| 
X| X| O| 
.| .| .| 

O| X| .| 
X| X| O| 
.| O| .| 

Evaluacion: 0.000241s
Movimientos Recomendados: X = 0, Y = 2
X coordenada: 0
Y coordenada: 2
O| X| X| 
X| X| O| 
.| O| .| 

O| X| X| 
X| X| O| 
O| O| .| 

Evaluacion: 2.98e-05s
Movimientos Recomendados: X = 2, Y = 2
X coordenada: 2
Y coordenada: 2
O| X| X| 
X| X| O| 
O| O| X| 

Empate!


# Ejercicio: ¿Puedes modificar las funciones min y max para podar las ramas innecesarias? ¿Que le pasa al tiempo de procesamiento de la busqueda de la IA?

Modifica las funciones min, max y jugar con los ejemplos siguientes rellenando los espacios:

In [11]:
def max_alfa_beta(self, alfa, beta):
        maxv = -2  # Inicializamos el valor máximo a un número bajo
        px = None  # Coordenada x para el mejor movimiento
        py = None  # Coordenada y para el mejor movimiento

        resultado = self.comprobar_resultado()  # Comprobar el estado del juego

        if resultado == 'X':  # Si el jugador 'X' gana
            return (-1, 0, 0)
        elif resultado == 'O':  # Si el jugador 'O' gana
            return (1, 0, 0)
        elif resultado == '.':  # Si es un empate
            return (0, 0, 0)

        for i in range(0, 3):  # Iteramos sobre las filas
            for j in range(0, 3):  # Iteramos sobre las columnas
                if self.estado_actual[i][j] == '.':  # Si la casilla está vacía
                    self.estado_actual[i][j] = 'O'  # Jugada del jugador 'O'
                    (m, min_i, min_j) = self.min_alfa_beta(alfa, beta)  # Llamada recursiva a min_alfa_beta

                    if m > maxv:  # Si encontramos un mejor valor
                        maxv = m
                        px = i
                        py = j

                    self.estado_actual[i][j] = '.'  # Deshacemos la jugada

                    if maxv >= beta:  # Poda beta: si maxv es mayor o igual que beta, no seguimos
                        return (maxv, px, py)

                    if maxv > alfa:  # Actualizamos alfa
                        alfa = maxv

        return (maxv, px, py)  # Devolvemos el mejor valor y la posición


In [12]:
def min_alfa_beta(self, alfa, beta):

        minv = 2  # Inicializamos con un valor alto, porque buscamos minimizar

        qx = None  # Coordenada x para el mejor movimiento
        qy = None  # Coordenada y para el mejor movimiento

        resultado = self.comprobar_resultado()  # Comprobar el estado del juego

        if resultado == 'X':  # Si 'X' gana
            return (-1, 0, 0)
        elif resultado == 'O':  # Si 'O' gana
            return (1, 0, 0)
        elif resultado == '.':  # Si es un empate
            return (0, 0, 0)

        for i in range(0, 3):  # Iteramos sobre las filas
            for j in range(0, 3):  # Iteramos sobre las columnas
                if self.estado_actual[i][j] == '.':  # Si la casilla está vacía
                    self.estado_actual[i][j] = 'X'  # Jugada del jugador 'X'
                    (m, max_i, max_j) = self.max_alfa_beta(alfa, beta)  # Llamada recursiva a max_alfa_beta

                    if m < minv:  # Si encontramos un mejor valor mínimo
                        minv = m
                        qx = i
                        qy = j

                    self.estado_actual[i][j] = '.'  # Deshacemos la jugada

                    if minv <= alfa:  # Poda alfa: si minv es menor o igual que alfa, no seguimos
                        return (minv, qx, qy)

                    if minv < beta:  # Actualizamos beta
                        beta = minv

        return (minv, qx, qy)  # Devolvemos el mejor valor y la posición


In [14]:
def jugar_alfa_beta(self):
     while True:
        self.mostrar_tablero()  # Mostramos el tablero actual
        self.resultado = self.comprobar_resultado()  # Comprobamos si hay un ganador o empate

        if self.resultado != None:  # Si hay un resultado (alguien ganó o empate)
            if self.resultado == 'X':
                print('¡Gana X!')
            elif self.resultado == 'O':
                print('¡Gana O!')
            elif self.resultado == '.':
                print("¡Empate!")

            self.mostrar_tablero()  # Mostramos el tablero final
            return  # Salimos del bucle y terminamos el juego

        if self.turno_actual == 'X':  # Si es el turno del jugador 'X'
            while True:
                inicio = time.time()  # Registramos el inicio del tiempo
                (m, qx, qy) = self.min_alfa_beta(-2, 2)  # Calculamos el mejor movimiento para 'X'
                fin = time.time()  # Registramos el fin del tiempo
                print('Tiempo de evaluación: {}s'.format(round(fin - inicio, 7)))
                print('Movimiento recomendado: X = {}, Y = {}'.format(qx, qy))

                px = int(input('X coordenada: '))  # Pedimos la coordenada x al jugador
                py = int(input('Y coordenada: '))  # Pedimos la coordenada y al jugador

                if self.es_movimiento_valido(px, py):  # Comprobamos si el movimiento es válido
                    self.estado_actual[px][py] = 'X'  # Hacemos el movimiento
                    self.turno_actual = 'O'  # Cambiamos el turno al jugador 'O'
                    break  # Salimos del bucle
                else:
                    print('Movimiento no válido. Prueba con otro movimiento.')

        else:  # Si es el turno del jugador 'O'
            (m, px, py) = self.max_alfa_beta(-2, 2)  # Calculamos el mejor movimiento para 'O'
            self.estado_actual[px][py] = 'O'  # Hacemos el movimiento para 'O'
            self.turno_actual = 'X'  # Cambiamos el turno al jugador 'X'
